services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3307:3306"  # Utiliser le bon port pour MariaDB
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###


  # Service app modifié pour utiliser notre Dockerfile
  app:
    build:

      context: .
      dockerfile: Dockerfile
    container_name: project-noor-design-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://root:@database:3306/noor?serverVersion=11&charset=utf8mb4"

