version: '3.8'

services:
  database:
    image: mariadb:11
    container_name: project-noor-design-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: noor
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: project-noor-design-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database

  mailer:
    image: axllent/mailpit
    container_name: project-noor-design-mailer
    restart: always
    ports:
      - "8025:8025"

volumes:
  database_data:


app:
  image: php:8.2-apache
  container_name: project-noor-design-app
  volumes:
    - .:/var/www/html
  ports:
    - "8080:80"
  depends_on:
    - database
  environment:
    DATABASE_URL: "mysql://root:@database:3306/noor?serverVersion=11&charset=utf8mb4"